version: '2'

services:
  botweb:
    image: botweb
    container_name: botweb
    ports:
    - 5000:5000
    - 5500:5500

  nginx:
    image: nginx_proxy
    container_name: production_nginx
    ports:
      - 4400:4400
    links:
      - botweb
